version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ms-email-db
    environment:
      POSTGRES_DB: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - gadata:/var/lib/postgresql/data

volumes:
  gadata: